packages:
  - .
  - apps/*
  - packages/*

minimumReleaseAge: 2880

catalog:
  '@playwright/test': ^1.60.0
  '@vitest/browser': ^4.1.7
  '@vitest/coverage-v8': ^4.1.7
  typescript: ^6.0.3
  vite: ^8.0.14
  vite-plus: ^0.1.22
  vitest: ^4.1.7

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
